Repository staticdev/ansible-role-pyenv, pull requests merged in 2023-06, with the labels that each got.

#204 Allow updating the pyenv global versions file
  tasks/install.yml
Labels: bug

#206 Add debian12 support
  .github/workflows/tests.yml
  LICENSE
Labels: enhancement

#207 Version 2.9.1
  current-version.txt
Labels: skip-changelog

#209 Version 2.10.0
  current-version.txt
Labels: skip-changelog
